server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Indispensable pour le routing Angular
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache pour les assets
    location ~* \.(js|css|png|jpg|ico|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}